language: python
python: 2.7
sudo: false
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libjansson-dev
      - libevent-dev
      - libssl-dev
      - git
install:
  - pip install cookiecutter
  - pip install Sphinx
script: |
  set -e
  CURDIR=$PWD
  cd /tmp
  cookiecutter --no-input $CURDIR
  cd bootstrap
  git init
  git submodule init
  git submodule add https://github.com/tatsuhiro-t/wslay.git
  (cd wslay ; git checkout release-1.0.0)
  ./autogen.sh
  ./configure
  make
  make distcheck
