name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 15 3 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install -qyy build-essential autoconf automake libtool libjansson-dev libevent-dev libssl-dev git npm
          pip install cookiecutter
          pip install sphinx
      - name: Build
        run: |
          CURDIR=$PWD
          cd /tmp
          cookiecutter --no-input $CURDIR
          cd bootstrap
          git init
          git submodule init
          git submodule add https://github.com/tatsuhiro-t/wslay.git
          (cd wslay ; git checkout release-1.0.0)
          ./autogen.sh
          ./configure
          (cd web ; npm install)
          make
